Add BlobFS test resource provider
aymanjarrousms/azure-storage-azcopy pull request #66
Opened 2023-08-31 03:33 UTC by shyaler

Add BlobFS resource provider to support e2e test operations.

2023-08-31 06:22 UTC, afekson commented on cmd/sync.go
> +	if cooked.followSymlinks && cooked.fromTo != common.EFromTo.LocalFile() && cooked.fromTo != common.EFromTo.LocalBlob() { // Follow symlinks in sync is supported only for local -> file or local -> bl
Why is this a part of this PR? How does it relates to E2E tests?

2023-08-31 07:08 UTC, shyaler commented on cmd/sync.go
> +	if cooked.followSymlinks && cooked.fromTo != common.EFromTo.LocalFile() && cooked.fromTo != common.EFromTo.LocalBlob() { // Follow symlinks in sync is supported only for local -> file or local -> bl
its a bug, found when tried to run the e2e tests. don't see a reason to create a separate PR just for this fix.

2023-08-31 07:58 UTC, afekson commented on cmd/sync.go
> +	if cooked.followSymlinks && cooked.fromTo != common.EFromTo.LocalFile() && cooked.fromTo != common.EFromTo.LocalBlob() { // Follow symlinks in sync is supported only for local -> file or local -> bl
can you please provide more details about the bug?

@OmarKhatib158

2023-09-03 13:09 UTC, OmarKhatib158 requested changes

2023-09-04 12:01 UTC, shmuelberezin approved these changes

2023-09-04 12:08 UTC, shmuelberezin commented on e2etest/declarativeResourceManagers.go
> +	panic("Not Implemented")
@shyaler, won't it fail in validateProperties?

2023-09-10 11:20 UTC, OmarKhatib158 commented on e2etest/declarativeResourceManagers.go
> +	panic("Not Implemented")
I will do it

2023-09-10 11:23 UTC, OmarKhatib158 approved these changes

2023-09-10 11:41 UTC, merged